# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
    ]
