# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(db_column='Teacher_id', primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(db_column='Teacher_Name', max_length=45)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('qualification', models.CharField(db_column='Qualification', max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('age', models.IntegerField(db_column='Age')),
                ('gender', models.CharField(db_column='Gender', max_length=45)),
                ('status', models.CharField(db_column='Status', max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('course', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
