# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
