# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('studymaterial_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_material', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'study_material',
                'managed': False,
            },
        ),
    ]
