# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('course', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
