# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('doubt_id', models.AutoField(primary_key=True, serialize=False)),
                ('doubt', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('doubt_reply', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doubt',
                'managed': False,
            },
        ),
    ]
