# Generated by Django 3.2.23 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('submission_date', models.DateField()),
                ('subject', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'assignment',
                'managed': False,
            },
        ),
    ]
